### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by chrishrb** [stong1994/github-copilot-api#1]
Hello,

Nice and useful project! Can you please add a LICENSE so we can use it as well?

Thanks in advance.
Christoph

**Comment by stong1994** [comment]
Dear Christoph,

I apologize for the delayed response to your comment. It seems I've been caught up in a whirlwind of tasks lately. I appreciate your patience and wanted to let you know that I've since added the license as requested.

Thank you for your understanding, and please let me know if there's anything else I can assist you with.

Best regards,
Stong

**Comment by chrishrb** [comment]
Thanks a lot, Stong! 👍
